import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "../store/StoreProvider";
import Tost from "./_component/Tost/tost"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">

      <body className={inter.className}>{children}
      <Tost/>
      </body>
    </html>
    </StoreProvider>
  );
}
